---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-bot-frontend-deployment
  labels:
    app: devops-bot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-bot-frontend
  template:
    metadata:
      labels:
        app: devops-bot-frontend
    spec:
      containers:
      - name: devops-bot-frontend
        image: deeeye2/devops-bot-frontend:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: devops-bot-frontend-service
spec:
  type: NodePort
  selector:
    app: devops-bot-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30004
